version: '3'

services:
  db:
    image: mongo
    volumes:
      - db:/data/db
  app:
    build: .
    volumes:
      - ./config:/app/config
    ports:
      - "8081:8100"

    depends_on:
      - db

volumes:
  db:
    driver: local